# Generated by Django 3.2.3 on 2021-05-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=50)),
                ('edate', models.CharField(max_length=50)),
                ('eloc', models.CharField(max_length=50)),
                ('enum', models.CharField(max_length=10)),
                ('edisc', models.CharField(max_length=50)),
            ],
        ),
    ]
