# Generated by Django 3.2.3 on 2021-05-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skedapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='etime',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='edate',
            field=models.CharField(max_length=20),
        ),
    ]
