# Generated by Django 3.2.3 on 2021-05-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skedapp', '0004_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=20)),
                ('phoneno', models.CharField(max_length=20)),
            ],
        ),
    ]
